defaults:
  - agent: representation_act_no_depth
  - benchmark: cholecystectomy_act

use_depth: False

# Experiment settings
seed: 0
device: cuda:0

dataloader:
  batch_size: 16
  num_workers: 0
  shuffle: True
  drop_last: True
  pin_memory: True

# Training settings
train:
  clip_grad_value: 0.0
  learning_rate: 0.001
  save_every_epochs: 10
  num_epochs: 100
  scheduler_instantiate_config:
    _target_: autonomous_surgery.helpers.pytorch.Optimizers.get_constant_scheduler
    lr: ${train.learning_rate}
    
# Evaluation settings
evaluation:
  num_skip_epochs: 0
  validation_frequency_epochs: 5
  validation_trajs_num: 25
  save_best_model: True

# Logging settings
wandb: # frequently used args
  project: SURPASS
  group: null
  name: ${agent.name}_${task_name}_${camera_name}
  notes: ${task_name}
  reinit: True
  mode: offline